UNIT_SIZE = 16
X = 17
Y = 13

SCREEN_POS = (0, 0)

DEFAULT_SCALE = 2.5

VIEWPORT_WIDTH = X * UNIT_SIZE
VIEWPORT_HEIGHT = Y * UNIT_SIZE

CENTER_WIDTH = (X // 2) * UNIT_SIZE
CENTER_HEIGHT = (Y // 2) * UNIT_SIZE

DEFAULT_SCREEN_WIDTH = VIEWPORT_WIDTH * DEFAULT_SCALE
DEFAULT_SCREEN_HEIGHT = VIEWPORT_HEIGHT * DEFAULT_SCALE