WINDOW_SPAWN = "5, 35"

UNIT_SIZE = 16
X = 17
Y = 13

DEFAULT_SCREEN_X = 0
DEFAULT_SCREEN_Y = 0

DEFAULT_SCALE = 2.5

VIEWPORT_WIDTH = X * UNIT_SIZE
VIEWPORT_HEIGHT = Y * UNIT_SIZE

DEFAULT_SCREEN_WIDTH = VIEWPORT_WIDTH * DEFAULT_SCALE
DEFAULT_SCREEN_HEIGHT = VIEWPORT_HEIGHT * DEFAULT_SCALE

CENTER_WIDTH = (X // 2) * UNIT_SIZE
CENTER_HEIGHT = (Y // 2) * UNIT_SIZE

DEFAULT_PLAYER_X = CENTER_WIDTH * DEFAULT_SCALE
DEFAULT_PLAYER_Y = CENTER_HEIGHT * DEFAULT_SCALE

# IMAGES:
PLAYER_SPRITE = "sprites/player.png"
LOCATION_SPRITE = "tiles/map.png"